"use client";

import React, { useState, useEffect, useMemo } from "react";
import {
  Gem, Ruler, ArrowRightLeft, Globe, 
  Info, CheckCircle2, Copy, AlertCircle,
  Activity, Sparkles
} from "lucide-react";

const RING_DATA = [
  { us: "3", uk: "F", eu: "44", dia: "14.1", circ: "44.2" },
  { us: "3.5", uk: "G", eu: "45", dia: "14.5", circ: "45.5" },
  { us: "4", uk: "H 1/2", eu: "47", dia: "14.9", circ: "46.8" },
  { us: "4.5", uk: "I 1/2", eu: "48", dia: "15.3", circ: "48.0" },
  { us: "5", uk: "J 1/2", eu: "49", dia: "15.7", circ: "49.3" },
  { us: "5.5", uk: "L", eu: "51", dia: "16.1", circ: "50.6" },
  { us: "6", uk: "M", eu: "52", dia: "16.5", circ: "51.9" },
  { us: "6.5", uk: "N", eu: "53", dia: "16.9", circ: "53.1" },
  { us: "7", uk: "O", eu: "54", dia: "17.3", circ: "54.4" },
  { us: "7.5", uk: "P", eu: "56", dia: "17.7", circ: "55.7" },
  { us: "8", uk: "Q", eu: "57", dia: "18.1", circ: "57.0" },
  { us: "8.5", uk: "Q 1/2", eu: "58", dia: "18.5", circ: "58.3" },
  { us: "9", uk: "R 1/2", eu: "59", dia: "18.9", circ: "59.5" },
  { us: "9.5", uk: "S 1/2", eu: "61", dia: "19.4", circ: "60.8" },
  { us: "10", uk: "T 1/2", eu: "62", dia: "19.8", circ: "62.1" },
  { us: "10.5", uk: "V", eu: "63", dia: "20.2", circ: "63.4" },
  { us: "11", uk: "W", eu: "64", dia: "20.6", circ: "64.6" },
  { us: "11.5", uk: "X", eu: "66", dia: "21.0", circ: "65.9" },
  { us: "12", uk: "Y", eu: "67", dia: "21.4", circ: "67.2" },
  { us: "12.5", uk: "Z", eu: "68", dia: "21.8", circ: "68.5" },
  { us: "13", uk: "Z+1", eu: "69", dia: "22.2", circ: "69.7" }
];

export default function RingSizeConverter() {
  const [isMounted, setIsMounted] = useState(false);

  const [inputMode, setInputMode] = useState("size");
  const [sourceRegion, setSourceRegion] = useState("us");
  const [selectedSize, setSelectedSize] = useState("7");
  const [measureType, setMeasureType] = useState("dia");
  const [measuredMm, setMeasuredMm] = useState("17.3");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const handleNumInput = (setter, value, max = null) => {
    if (value === "") {
      setter("");
      return;
    }
    if (/^\d*\.?\d*$/.test(value)) {
      const num = parseFloat(value);
      if (max && num > max) return;
      setter(value);
    }
  };

  const result = useMemo(() => {
    if (inputMode === "size") {
      return RING_DATA.find(item => item[sourceRegion] === selectedSize) || RING_DATA[8];
    } else {
      const mmVal = parseFloat(measuredMm) || 0;
      let closest = RING_DATA[0];
      let minDiff = Infinity;
      RING_DATA.forEach(item => {
        const targetVal = parseFloat(item[measureType]);
        const diff = Math.abs(targetVal - mmVal);
        if (diff < minDiff) {
          minDiff = diff;
          closest = item;
        }
      });
      return closest;
    }
  }, [inputMode, sourceRegion, selectedSize, measureType, measuredMm]);

  const handleCopy = () => {
    const text = `💍 My Ring Size Passport:\nUS: ${result.us}\nUK/AU: ${result.uk}\nEU: ${result.eu}\nInside Diameter: ${result.dia} mm\nCircumference: ${result.circ} mm\n\nGenerated by Utility Engine`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const baseInputStyle = "w-full min-w-0 bg-surface border border-line rounded-xl px-3.5 py-3 text-base font-bold text-ink outline-none focus:border-brand tabular-nums";

  return (
    <div className="mx-auto w-full max-w-7xl space-y-4 sm:space-y-6 overflow-x-hidden text-ink relative">
      
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-surface border border-line px-5 sm:px-6 py-5 rounded-2xl shadow-card relative overflow-hidden min-w-0">
        <div className="flex items-center gap-3.5 sm:gap-4 min-w-0">
          <div className="bg-brand/15 text-brand p-3 rounded-xl shrink-0">
            <Gem className="w-6 h-6" />
          </div>
          <div className="min-w-0">
            <h2 className="text-xl sm:text-2xl font-bold text-ink tracking-tight truncate">
              Ring Size Oracle
            </h2>
            <p className="text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-muted mt-0.5 truncate">
              Global Sizing & MM Measurement Engine
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr,460px] gap-6 items-start min-w-0">
        
        {/* CONFIGURATION ENGINE */}
        <div className="space-y-6 min-w-0">
          <div className="bg-surface border border-line p-5 sm:p-8 rounded-2xl shadow-card space-y-6 min-w-0">
            
            {/* Input Mode Toggle */}
            <div className="space-y-2.5 min-w-0">
              <label className="text-[10px] font-black text-muted uppercase tracking-widest flex items-center gap-1.5 truncate">
                <Sparkles className="w-3.5 h-3.5 text-brand shrink-0" /> 1. Conversion Method
              </label>
              
              <div className="grid grid-cols-2 gap-2.5 min-w-0">
                <button 
                  type="button"
                  onClick={() => setInputMode("size")}
                  className={`p-3.5 rounded-xl border transition-all flex flex-col items-start gap-1 min-w-0 truncate ${inputMode === "size" ? "border-brand bg-brand/5 text-ink" : "border-line bg-paper text-muted hover:text-ink"}`}
                >
                  <ArrowRightLeft className={`w-4 h-4 shrink-0 ${inputMode === "size" ? "text-brand" : "text-muted"}`} />
                  <span className="text-[10px] font-black uppercase tracking-wider truncate w-full text-left">Standard Convert</span>
                  <span className="text-[8px] font-bold text-muted truncate w-full text-left">US, UK, EU</span>
                </button>
                
                <button 
                  type="button"
                  onClick={() => setInputMode("measure")}
                  className={`p-3.5 rounded-xl border transition-all flex flex-col items-start gap-1 min-w-0 truncate ${inputMode === "measure" ? "border-brand bg-brand/5 text-ink" : "border-line bg-paper text-muted hover:text-ink"}`}
                >
                  <Ruler className={`w-4 h-4 shrink-0 ${inputMode === "measure" ? "text-brand" : "text-muted"}`} />
                  <span className="text-[10px] font-black uppercase tracking-wider truncate w-full text-left">True Measure</span>
                  <span className="text-[8px] font-bold text-muted truncate w-full text-left">By millimeter (MM)</span>
                </button>
              </div>
            </div>

            <hr className="border-line" />

            {/* Dynamic Inputs based on mode */}
            {inputMode === "size" ? (
              <div className="space-y-3 min-w-0">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 min-w-0">
                  <div className="min-w-0">
                    <label className="text-[8px] font-bold text-muted uppercase tracking-widest mb-1 block truncate">Source Region</label>
                    <select
                      value={sourceRegion} onChange={(e) => setSourceRegion(e.target.value)}
                      className={`${baseInputStyle} cursor-pointer uppercase truncate`}
                    >
                      <option value="us">US / Canada</option>
                      <option value="uk">UK / Australia</option>
                      <option value="eu">Europe (EU)</option>
                    </select>
                  </div>
                  <div className="min-w-0">
                    <label className="text-[8px] font-bold text-muted uppercase tracking-widest mb-1 block truncate">Select Size</label>
                    <select
                      value={selectedSize} onChange={(e) => setSelectedSize(e.target.value)}
                      className={`${baseInputStyle} cursor-pointer truncate`}
                    >
                      {RING_DATA.map((item, idx) => (
                        <option key={idx} value={item[sourceRegion]}>{item[sourceRegion]}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-3 min-w-0">
                <div className="flex bg-paper rounded-xl p-1 border border-line min-w-0 gap-1">
                  <button 
                    type="button"
                    onClick={() => setMeasureType("dia")}
                    className={`flex-1 py-2 text-[9px] font-black uppercase tracking-wider rounded-lg transition-all truncate ${measureType === "dia" ? "bg-surface text-brand shadow-sm border border-line" : "text-muted hover:text-ink"}`}
                  >
                    Inside Diameter
                  </button>
                  <button 
                    type="button"
                    onClick={() => setMeasureType("circ")}
                    className={`flex-1 py-2 text-[9px] font-black uppercase tracking-wider rounded-lg transition-all truncate ${measureType === "circ" ? "bg-surface text-brand shadow-sm border border-line" : "text-muted hover:text-ink"}`}
                  >
                    Circumference
                  </button>
                </div>
                
                <div className="space-y-1.5 min-w-0">
                  <label className="text-[9px] font-bold text-muted uppercase tracking-widest block truncate">
                    {measureType === 'dia' ? "Inside diameter of existing ring" : "Circumference via string wrap"}
                  </label>
                  <div className="relative flex items-center bg-paper border border-line rounded-xl overflow-hidden focus-within:border-brand min-w-0">
                    <div className="bg-surface px-3 py-3.5 flex items-center justify-center border-r border-line shrink-0">
                      <Ruler className="w-4 h-4 text-muted" />
                    </div>
                    <input
                      type="text" value={measuredMm} 
                      onChange={(e) => handleNumInput(setMeasuredMm, e.target.value, 100)}
                      placeholder="17.3"
                      className="w-full min-w-0 bg-transparent px-3 py-3 text-2xl font-black text-ink outline-none tabular-nums"
                    />
                    <span className="pr-4 text-xs font-bold text-muted uppercase tracking-wider pointer-events-none">MM</span>
                  </div>
                </div>
              </div>
            )}

          </div>
        </div>

        {/* DASHBOARD / PASSPORT */}
        <div className="space-y-6 lg:sticky lg:top-6 min-w-0">
          <div className="bg-surface border border-line p-5 sm:p-6 rounded-2xl shadow-card flex flex-col min-h-[500px] min-w-0">
            
            <div className="flex items-center justify-between mb-4 border-b border-line pb-3 shrink-0 min-w-0">
              <span className="inline-flex items-center gap-1.5 text-xs font-black uppercase tracking-widest text-ink truncate">
                <Activity className="w-4 h-4 text-brand shrink-0" /> Size Passport
              </span>
              <span className="text-[9px] font-bold uppercase tracking-wider text-muted bg-paper px-2 py-0.5 rounded border border-line shrink-0">
                Jeweler Standard
              </span>
            </div>

            {/* HERO METRIC: US SIZE */}
            <div className="text-center bg-paper border border-line py-5 px-4 rounded-xl shadow-sm mb-4 relative overflow-hidden shrink-0 min-w-0">
              <span className="block text-[9px] font-black uppercase tracking-widest text-muted mb-1 truncate">
                Target US Size
              </span>
              <div className="flex justify-center items-center min-w-0">
                <span className="text-4xl sm:text-5xl font-black text-brand tracking-tight leading-none truncate">
                  {result.us}
                </span>
              </div>
              
              {inputMode === "measure" && (
                <div className="mt-3 flex justify-center min-w-0">
                  <span className="text-[8px] font-black uppercase tracking-widest px-2.5 py-1 rounded-full bg-surface border border-line text-muted truncate">
                    Closest Match Auto-Selected
                  </span>
                </div>
              )}
            </div>

            {/* COUNTRY CONVERSIONS GRID */}
            <div className="grid grid-cols-2 gap-2.5 mb-4 shrink-0 min-w-0">
              <div className="flex flex-col items-center justify-center p-3 rounded-xl border border-line bg-paper min-w-0 truncate">
                <span className="text-[8px] font-black text-muted uppercase tracking-wider truncate">UK / AU Size</span>
                <span className="text-lg sm:text-xl font-black text-ink mt-0.5 truncate">{result.uk}</span>
              </div>
              <div className="flex flex-col items-center justify-center p-3 rounded-xl border border-line bg-paper min-w-0 truncate">
                <span className="text-[8px] font-black text-muted uppercase tracking-wider truncate">EU Size</span>
                <span className="text-lg sm:text-xl font-black text-ink mt-0.5 truncate">{result.eu}</span>
              </div>
            </div>

            {/* PHYSICAL MEASUREMENTS */}
            <div className="flex-1 flex flex-col min-h-0 bg-paper rounded-xl border border-line p-2 shadow-sm mb-4 min-w-0 text-xs">
              <div className="flex items-center gap-1.5 text-[9px] font-black uppercase tracking-widest text-ink px-2.5 py-2 border-b border-line shrink-0 truncate">
                <Ruler className="w-3.5 h-3.5 text-brand shrink-0" /> Physical Blueprint
              </div>

              <div className="flex-1 overflow-y-auto custom-scrollbar p-2 space-y-1.5 min-w-0">
                <div className="flex items-center justify-between p-2.5 bg-surface rounded-lg min-w-0">
                  <span className="font-bold text-muted truncate">Inside Diameter</span>
                  <span className="font-black text-ink tabular-nums shrink-0">{result.dia} mm</span>
                </div>

                <div className="flex items-center justify-between p-2.5 bg-surface rounded-lg min-w-0">
                  <span className="font-bold text-muted truncate">Circumference</span>
                  <span className="font-black text-ink tabular-nums shrink-0">{result.circ} mm</span>
                </div>
              </div>
            </div>
            
            {/* Pro Tips Insight */}
            <div className="mb-4 flex items-start gap-2 min-w-0 shrink-0">
              <AlertCircle className="w-3.5 h-3.5 text-amber-500 shrink-0 mt-0.5" />
              <p className="text-[9px] font-medium text-muted leading-relaxed truncate">
                <strong>Tip:</strong> Wide bands (&gt;4mm) need +0.5 size. Measure end of day.
              </p>
            </div>

            {/* ACTION BUTTON */}
            <button
              type="button"
              onClick={handleCopy}
              className="w-full py-3.5 rounded-xl bg-ink text-surface hover:opacity-95 text-xs font-black uppercase tracking-widest transition-opacity flex items-center justify-center gap-2 shrink-0"
            >
              {copied ? <><CheckCircle2 className="w-3.5 h-3.5 shrink-0"/> Copied!</> : <><Copy className="w-3.5 h-3.5 shrink-0"/> Copy Size Passport</>}
            </button>

          </div>
        </div>

      </div>
    </div>
  );
}