"use client";

import React, { useState, useEffect, useMemo } from "react";
import {
  Gem, Ruler, ArrowRightLeft, Globe, 
  Info, CheckCircle2, Copy, AlertCircle,
  Activity, Sparkles
} from "lucide-react";

// Robust Global Ring Sizing Database (US, UK, EU, Diameter MM, Circumference MM)
const RING_DATA = [
  { us: "3", uk: "F", eu: "44", dia: "14.1", circ: "44.2" },
  { us: "3.5", uk: "G", eu: "45", dia: "14.5", circ: "45.5" },
  { us: "4", uk: "H 1/2", eu: "47", dia: "14.9", circ: "46.8" },
  { us: "4.5", uk: "I 1/2", eu: "48", dia: "15.3", circ: "48.0" },
  { us: "5", uk: "J 1/2", eu: "49", dia: "15.7", circ: "49.3" },
  { us: "5.5", uk: "L", eu: "51", dia: "16.1", circ: "50.6" },
  { us: "6", uk: "M", eu: "52", dia: "16.5", circ: "51.9" },
  { us: "6.5", uk: "N", eu: "53", dia: "16.9", circ: "53.1" },
  { us: "7", uk: "O", eu: "54", dia: "17.3", circ: "54.4" },
  { us: "7.5", uk: "P", eu: "56", dia: "17.7", circ: "55.7" },
  { us: "8", uk: "Q", eu: "57", dia: "18.1", circ: "57.0" },
  { us: "8.5", uk: "Q 1/2", eu: "58", dia: "18.5", circ: "58.3" },
  { us: "9", uk: "R 1/2", eu: "59", dia: "18.9", circ: "59.5" },
  { us: "9.5", uk: "S 1/2", eu: "61", dia: "19.4", circ: "60.8" },
  { us: "10", uk: "T 1/2", eu: "62", dia: "19.8", circ: "62.1" },
  { us: "10.5", uk: "V", eu: "63", dia: "20.2", circ: "63.4" },
  { us: "11", uk: "W", eu: "64", dia: "20.6", circ: "64.6" },
  { us: "11.5", uk: "X", eu: "66", dia: "21.0", circ: "65.9" },
  { us: "12", uk: "Y", eu: "67", dia: "21.4", circ: "67.2" },
  { us: "12.5", uk: "Z", eu: "68", dia: "21.8", circ: "68.5" },
  { us: "13", uk: "Z+1", eu: "69", dia: "22.2", circ: "69.7" }
];

export default function RingSizeConverter() {
  const [isMounted, setIsMounted] = useState(false);

  // States
  const [inputMode, setInputMode] = useState("size"); // 'size' or 'measure'
  
  // Size Mode States
  const [sourceRegion, setSourceRegion] = useState("us"); // 'us', 'uk', 'eu'
  const [selectedSize, setSelectedSize] = useState("7");
  
  // Measure Mode States
  const [measureType, setMeasureType] = useState("dia"); // 'dia' (Diameter) or 'circ' (Circumference)
  const [measuredMm, setMeasuredMm] = useState("17.3");
  
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const handleNumInput = (setter, value, max = null) => {
    if (value === "") {
      setter("");
      return;
    }
    if (/^\d*\.?\d*$/.test(value)) {
      const num = parseFloat(value);
      if (max && num > max) return;
      setter(value);
    }
  };

  // --- CORE CONVERSION ENGINE ---
  const result = useMemo(() => {
    if (inputMode === "size") {
      // Exact Match
      return RING_DATA.find(item => item[sourceRegion] === selectedSize) || RING_DATA[8];
    } else {
      // Find CLOSEST match based on MM input
      const mmVal = parseFloat(measuredMm) || 0;
      let closest = RING_DATA[0];
      let minDiff = Infinity;
      
      RING_DATA.forEach(item => {
        const targetVal = parseFloat(item[measureType]);
        const diff = Math.abs(targetVal - mmVal);
        if (diff < minDiff) {
          minDiff = diff;
          closest = item;
        }
      });
      return closest;
    }
  }, [inputMode, sourceRegion, selectedSize, measureType, measuredMm]);

  const handleCopy = () => {
    const text = `💍 My Ring Size Passport:\nUS: ${result.us}\nUK/AU: ${result.uk}\nEU: ${result.eu}\nInside Diameter: ${result.dia} mm\nCircumference: ${result.circ} mm\n\nGenerated by Muxair Utility Engine`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isMounted) return null;

  // Premium Rose Gold Theme Variables
  const theme = {
    gradient: "from-rose-100 via-amber-50 to-transparent dark:from-rose-900/30 dark:via-amber-900/10",
    bgIcon: "bg-gradient-to-br from-rose-400 to-amber-500",
    textPri: "text-rose-600 dark:text-rose-400",
    borderLight: "border-rose-200 dark:border-rose-800",
    bgLight: "bg-rose-50 dark:bg-rose-900/20"
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 font-sans">
      
      {/* Premium Header */}
      <div className={`flex flex-wrap items-center justify-between gap-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 px-6 py-6 rounded-2xl shadow-sm relative overflow-hidden transition-colors duration-500`}>
        <div className={`absolute top-0 right-0 w-72 h-72 bg-gradient-to-bl ${theme.gradient} rounded-bl-full -z-10 opacity-70`}></div>
        <div className="flex items-center gap-4">
          <div className={`${theme.bgIcon} p-3.5 rounded-2xl shadow-md`}>
            <Gem className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-black text-slate-800 dark:text-slate-100 tracking-tight">
              Ring Size Oracle
            </h2>
            <p className="text-[11px] font-bold uppercase tracking-widest text-slate-400 mt-1">
              Global Sizing & MM Measurement Engine
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr,460px] gap-6 items-start">
        
        {/* ================= LEFT: CONFIGURATION ENGINE ================= */}
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 sm:p-8 rounded-3xl shadow-sm space-y-8">
            
            {/* 1. Input Mode Toggle */}
            <div className="space-y-4">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-400 flex items-center gap-1.5 border-b border-slate-100 dark:border-slate-800 pb-2">
                <Sparkles className={`w-3.5 h-3.5 ${theme.textPri}`} /> 1. Conversion Method
              </h3>
              
              <div className="grid grid-cols-2 gap-3">
                <button 
                  onClick={() => setInputMode("size")}
                  className={`p-4 rounded-2xl border-2 transition-all flex flex-col items-start gap-1.5 ${inputMode === "size" ? `${theme.borderLight} ${theme.bgLight}` : "border-slate-200 dark:border-slate-700 hover:border-slate-300 bg-slate-50 dark:bg-slate-800/50"}`}
                >
                  <ArrowRightLeft className={`w-5 h-5 ${inputMode === "size" ? theme.textPri : "text-slate-400"}`} />
                  <span className={`text-xs font-black uppercase tracking-widest ${inputMode === "size" ? theme.textPri : "text-slate-600 dark:text-slate-400"}`}>Standard Convert</span>
                  <span className="text-[10px] font-bold text-slate-400 text-left">Convert US, UK, EU</span>
                </button>
                
                <button 
                  onClick={() => setInputMode("measure")}
                  className={`p-4 rounded-2xl border-2 transition-all flex flex-col items-start gap-1.5 ${inputMode === "measure" ? `${theme.borderLight} ${theme.bgLight}` : "border-slate-200 dark:border-slate-700 hover:border-slate-300 bg-slate-50 dark:bg-slate-800/50"}`}
                >
                  <Ruler className={`w-5 h-5 ${inputMode === "measure" ? theme.textPri : "text-slate-400"}`} />
                  <span className={`text-xs font-black uppercase tracking-widest ${inputMode === "measure" ? theme.textPri : "text-slate-600 dark:text-slate-400"}`}>True Measure (MM)</span>
                  <span className="text-[10px] font-bold text-slate-400 text-left">Find size by millimeter</span>
                </button>
              </div>
            </div>

            <hr className="border-slate-100 dark:border-slate-800" />

            {/* 2. Dynamic Inputs based on mode */}
            {inputMode === "size" ? (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5 block flex items-center gap-1.5">
                      <Globe className="w-3.5 h-3.5" /> Source Region
                    </label>
                    <select
                      value={sourceRegion} onChange={(e) => setSourceRegion(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-xl px-4 py-4 text-sm font-black text-slate-800 dark:text-slate-100 outline-none focus:border-rose-400 cursor-pointer uppercase tracking-widest"
                    >
                      <option value="us">US / Canada</option>
                      <option value="uk">UK / Australia</option>
                      <option value="eu">Europe (EU)</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5 block">Select Known Size</label>
                    <select
                      value={selectedSize} onChange={(e) => setSelectedSize(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-xl px-4 py-4 text-lg font-black text-slate-800 dark:text-slate-100 outline-none cursor-pointer focus:border-rose-400 transition-colors"
                    >
                      {RING_DATA.map((item, idx) => (
                        <option key={idx} value={item[sourceRegion]}>{item[sourceRegion]}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                <div className="flex bg-slate-100 dark:bg-slate-800 rounded-xl p-1 shadow-inner mb-4">
                  <button 
                    onClick={() => setMeasureType("dia")}
                    className={`flex-1 py-3 text-[10px] sm:text-xs font-black uppercase tracking-widest rounded-lg transition-all ${measureType === "dia" ? "bg-white dark:bg-slate-700 text-rose-600 shadow-sm" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
                  >
                    Inside Diameter
                  </button>
                  <button 
                    onClick={() => setMeasureType("circ")}
                    className={`flex-1 py-3 text-[10px] sm:text-xs font-black uppercase tracking-widest rounded-lg transition-all ${measureType === "circ" ? "bg-white dark:bg-slate-700 text-rose-600 shadow-sm" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
                  >
                    Circumference (String)
                  </button>
                </div>
                
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5 block">
                  {measureType === 'dia' ? "Measure the INSIDE across an existing ring" : "Wrap a string around your finger and measure"}
                </label>
                <div className={`relative flex items-center bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-2xl overflow-hidden focus-within:border-rose-400 transition-all`}>
                  <div className="bg-slate-100 dark:bg-slate-800 px-5 py-5 flex items-center justify-center border-r border-slate-200 dark:border-slate-700">
                    <Ruler className="w-5 h-5 text-slate-400" />
                  </div>
                  <input
                    type="text" value={measuredMm} 
                    onChange={(e) => handleNumInput(setMeasuredMm, e.target.value, 100)}
                    placeholder="17.3"
                    className="w-full bg-transparent px-5 py-5 text-3xl font-black text-slate-800 dark:text-slate-100 outline-none tabular-nums"
                  />
                  <span className="pr-6 text-sm font-bold text-slate-400 uppercase tracking-widest">MM</span>
                </div>
              </div>
            )}

          </div>
        </div>

        {/* ================= RIGHT: THE DASHBOARD / PASSPORT ================= */}
        <div className="space-y-6 sticky top-6">
          <div className="bg-white dark:bg-[#0d1117] border border-slate-200 dark:border-slate-800 p-1 rounded-3xl shadow-lg relative flex flex-col min-h-[640px]">
            <div className="bg-slate-50 dark:bg-slate-900/50 rounded-[22px] p-6 h-full flex flex-col relative overflow-hidden">
              
              <div className="flex items-center justify-between mb-4 border-b border-slate-200 dark:border-slate-700 pb-4 shrink-0">
                <span className="inline-flex items-center gap-1.5 text-xs font-black uppercase tracking-widest text-slate-800 dark:text-slate-100">
                  <Activity className={`w-4 h-4 ${theme.textPri}`} /> Size Passport
                </span>
                <span className={`text-[9px] font-bold uppercase tracking-widest ${theme.textPri} bg-white dark:bg-slate-800 px-2 py-1 rounded shadow-sm border border-slate-100 dark:border-slate-700`}>
                  Jeweler's Standard
                </span>
              </div>

              {/* HERO METRIC: US SIZE (Global Standard in Jewelry) */}
              <div className="text-center bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 py-6 px-4 rounded-3xl shadow-sm mb-6 relative overflow-hidden shrink-0">
                <div className="absolute -left-4 -bottom-4 opacity-5 pointer-events-none">
                  <Gem className={`w-32 h-32 ${theme.textPri}`} />
                </div>
                
                <span className="block text-[10px] font-black uppercase tracking-widest text-slate-400 mb-1 z-10 relative">
                  Target US Size
                </span>
                <div className="flex justify-center items-center z-10 relative">
                  <span className={`text-6xl sm:text-7xl font-black ${theme.textPri} tracking-tighter leading-none`}>
                    {result.us}
                  </span>
                </div>
                
                {inputMode === "measure" && (
                  <div className="mt-4 flex justify-center z-10 relative">
                    <span className="text-[9px] font-black uppercase tracking-widest px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 border border-slate-200 dark:border-slate-700">
                      Closest Match Automatically Selected
                    </span>
                  </div>
                )}
              </div>

              {/* COUNTRY CONVERSIONS GRID */}
              <div className="grid grid-cols-2 gap-3 mb-6 shrink-0">
                <div className="flex flex-col items-center justify-center p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-sm">
                  <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">UK / AU Size</span>
                  <span className="text-2xl font-black text-slate-800 dark:text-slate-100">{result.uk}</span>
                </div>
                <div className="flex flex-col items-center justify-center p-4 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-sm">
                  <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">EU Size</span>
                  <span className="text-2xl font-black text-slate-800 dark:text-slate-100">{result.eu}</span>
                </div>
              </div>

              {/* PHYSICAL MEASUREMENTS */}
              <div className={`flex-1 flex flex-col min-h-0 bg-white dark:bg-slate-900 rounded-2xl border ${theme.borderLight} p-1 shadow-sm mb-4`}>
                <div className={`flex items-center gap-1.5 text-[10px] font-black uppercase tracking-widest ${theme.textPri} px-4 py-3 border-b border-slate-100 dark:border-slate-800 shrink-0 bg-slate-50 dark:bg-slate-900/50 rounded-t-xl`}>
                  <Ruler className="w-3.5 h-3.5" /> Physical Blueprint
                </div>

                <div className="flex-1 overflow-y-auto custom-scrollbar p-3 space-y-2">
                  
                  <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-800/50 rounded-lg">
                    <span className="text-xs font-bold text-slate-500">Inside Diameter</span>
                    <div className="text-right">
                      <span className="text-sm font-black text-slate-800 dark:text-slate-100 block">{result.dia} mm</span>
                    </div>
                  </div>

                  <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-800/50 rounded-lg">
                    <span className="text-xs font-bold text-slate-500">Circumference</span>
                    <div className="text-right">
                      <span className="text-sm font-black text-slate-800 dark:text-slate-100 block">{result.circ} mm</span>
                    </div>
                  </div>

                </div>
              </div>
              
              {/* Pro Tips Insight */}
              <div className="mb-4 pb-2 flex items-start gap-2">
                <AlertCircle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                <p className="text-[10px] font-medium text-slate-500 leading-relaxed">
                  <strong>Jeweler's Tip:</strong> If you are buying a wide-band ring (thicker than 4mm), always go up <strong>half a size</strong> for a comfortable fit. Your fingers also swell in heat, so measure at the end of the day.
                </p>
              </div>

              {/* ACTION BUTTON */}
              <button
                onClick={handleCopy}
                className="w-full py-4 rounded-xl bg-slate-800 dark:bg-slate-100 hover:bg-slate-700 dark:hover:bg-white text-white dark:text-slate-900 text-xs font-black uppercase tracking-widest transition-colors flex items-center justify-center gap-2 shrink-0 mt-auto"
              >
                {copied ? <><CheckCircle2 className="w-4 h-4"/> Saved to Clipboard!</> : <><Copy className="w-4 h-4"/> Copy Size Passport</>}
              </button>

            </div>
          </div>
        </div>

      </div>
    </div>
  );
}