"use client";

import React, { useState, useEffect, useMemo } from "react";
import {
  Globe, Ruler, ShoppingBag, Info, 
  CheckCircle2, Copy, AlertCircle, ArrowRightLeft,
  Settings2, Activity
} from "lucide-react";

const SHOE_DATA = {
  men: [
    { us: "6", uk: "5.5", eu: "39", cm: "24.0" },
    { us: "6.5", uk: "6", eu: "39.5", cm: "24.5" },
    { us: "7", uk: "6", eu: "40", cm: "25.0" },
    { us: "7.5", uk: "6.5", eu: "40.5", cm: "25.5" },
    { us: "8", uk: "7", eu: "41", cm: "26.0" },
    { us: "8.5", uk: "7.5", eu: "42", cm: "26.5" },
    { us: "9", uk: "8", eu: "42.5", cm: "27.0" },
    { us: "9.5", uk: "8.5", eu: "43", cm: "27.5" },
    { us: "10", uk: "9", eu: "44", cm: "28.0" },
    { us: "10.5", uk: "9.5", eu: "44.5", cm: "28.5" },
    { us: "11", uk: "10", eu: "45", cm: "29.0" },
    { us: "11.5", uk: "10.5", eu: "45.5", cm: "29.5" },
    { us: "12", uk: "11", eu: "46", cm: "30.0" },
    { us: "13", uk: "12", eu: "47.5", cm: "31.0" },
    { us: "14", uk: "13", eu: "48.5", cm: "32.0" }
  ],
  women: [
    { us: "5", uk: "3", eu: "35.5", cm: "22.0" },
    { us: "5.5", uk: "3.5", eu: "36", cm: "22.5" },
    { us: "6", uk: "4", eu: "36.5", cm: "23.0" },
    { us: "6.5", uk: "4.5", eu: "37.5", cm: "23.5" },
    { us: "7", uk: "5", eu: "38", cm: "24.0" },
    { us: "7.5", uk: "5.5", eu: "38.5", cm: "24.5" },
    { us: "8", uk: "6", eu: "39", cm: "25.0" },
    { us: "8.5", uk: "6.5", eu: "40", cm: "25.5" },
    { us: "9", uk: "7", eu: "40.5", cm: "26.0" },
    { us: "9.5", uk: "7.5", eu: "41", cm: "26.5" },
    { us: "10", uk: "8", eu: "42", cm: "27.0" },
    { us: "10.5", uk: "8.5", eu: "42.5", cm: "27.5" },
    { us: "11", uk: "9", eu: "43", cm: "28.0" },
    { us: "12", uk: "10", eu: "44.5", cm: "29.0" }
  ],
  kids: [
    { us: "1Y", uk: "13.5", eu: "32", cm: "20.0" },
    { us: "1.5Y", uk: "1", eu: "33", cm: "20.5" },
    { us: "2Y", uk: "1.5", eu: "33.5", cm: "21.0" },
    { us: "2.5Y", uk: "2", eu: "34", cm: "21.5" },
    { us: "3Y", uk: "2.5", eu: "35", cm: "22.0" },
    { us: "3.5Y", uk: "3", eu: "35.5", cm: "22.5" },
    { us: "4Y", uk: "3.5", eu: "36", cm: "23.0" },
    { us: "4.5Y", uk: "4", eu: "36.5", cm: "23.5" },
    { us: "5Y", uk: "4.5", eu: "37.5", cm: "23.5" },
    { us: "6Y", uk: "5.5", eu: "38.5", cm: "24.0" }
  ]
};

export default function ShoeSizeConverter() {
  const [isMounted, setIsMounted] = useState(false);

  const [profile, setProfile] = useState("men");
  const [inputMode, setInputMode] = useState("size");
  const [sourceRegion, setSourceRegion] = useState("us");
  const [selectedSize, setSelectedSize] = useState("9");
  const [measuredCm, setMeasuredCm] = useState("27.0");
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const data = SHOE_DATA[profile];
    if (data && data.length > 0) {
      if (inputMode === "size") {
        const midIndex = Math.floor(data.length / 2);
        setSelectedSize(data[midIndex][sourceRegion]);
      } else {
        const midIndex = Math.floor(data.length / 2);
        setMeasuredCm(data[midIndex].cm);
      }
    }
  }, [profile, sourceRegion, inputMode]);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const result = useMemo(() => {
    const data = SHOE_DATA[profile];
    if (inputMode === "size") {
      return data.find(item => item[sourceRegion] === selectedSize) || data[0];
    } else {
      const cmVal = parseFloat(measuredCm) || 0;
      let closest = data[0];
      let minDiff = Infinity;
      data.forEach(item => {
        const diff = Math.abs(parseFloat(item.cm) - cmVal);
        if (diff < minDiff) {
          minDiff = diff;
          closest = item;
        }
      });
      return closest;
    }
  }, [profile, inputMode, sourceRegion, selectedSize, measuredCm]);

  const handleCopy = () => {
    const text = `👟 My Shoe Size Passport (${profile.toUpperCase()}):\nUS: ${result.us}\nUK: ${result.uk}\nEU: ${result.eu}\nFoot Length: ${result.cm} CM\n\nGenerated by Utility Engine`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isMounted) return null;

  const baseInputStyle = "w-full min-w-0 bg-surface border border-line rounded-xl px-3.5 py-3 text-base font-bold text-ink outline-none focus:border-brand tabular-nums";

  return (
    <div className="mx-auto w-full max-w-7xl space-y-4 sm:space-y-6 overflow-x-hidden text-ink relative">
      
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-surface border border-line px-5 sm:px-6 py-5 rounded-2xl shadow-card relative overflow-hidden min-w-0">
        <div className="flex items-center gap-3.5 sm:gap-4 min-w-0">
          <div className="bg-brand/15 text-brand p-3 rounded-xl shrink-0">
            <Globe className="w-6 h-6" />
          </div>
          <div className="min-w-0">
            <h2 className="text-xl sm:text-2xl font-bold text-ink tracking-tight truncate">
              Global Sizing Engine
            </h2>
            <p className="text-[10px] sm:text-[11px] font-bold uppercase tracking-widest text-muted mt-0.5 truncate">
              Universal Shoe Size & Fit Converter
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr,460px] gap-6 items-start min-w-0">
        
        {/* CONFIGURATION ENGINE */}
        <div className="space-y-6 min-w-0">
          <div className="bg-surface border border-line p-5 sm:p-8 rounded-2xl shadow-card space-y-6 min-w-0">
            
            {/* Demographic Profile */}
            <div className="space-y-2.5 min-w-0">
              <label className="text-[10px] font-black text-muted uppercase tracking-widest flex items-center gap-1.5 truncate">
                <ShoppingBag className="w-3.5 h-3.5 text-brand shrink-0" /> 1. Select Demographic
              </label>
              <div className="flex bg-paper rounded-xl p-1 border border-line min-w-0 gap-1">
                <button 
                  type="button"
                  onClick={() => setProfile("men")}
                  className={`flex-1 py-2.5 text-[11px] font-black uppercase tracking-wider rounded-lg transition-all truncate ${profile === "men" ? "bg-surface text-brand shadow-sm border border-line" : "text-muted hover:text-ink"}`}
                >
                  Men
                </button>
                <button 
                  type="button"
                  onClick={() => setProfile("women")}
                  className={`flex-1 py-2.5 text-[11px] font-black uppercase tracking-wider rounded-lg transition-all truncate ${profile === "women" ? "bg-surface text-brand shadow-sm border border-line" : "text-muted hover:text-ink"}`}
                >
                  Women
                </button>
                <button 
                  type="button"
                  onClick={() => setProfile("kids")}
                  className={`flex-1 py-2.5 text-[11px] font-black uppercase tracking-wider rounded-lg transition-all truncate ${profile === "kids" ? "bg-surface text-brand shadow-sm border border-line" : "text-muted hover:text-ink"}`}
                >
                  Youth
                </button>
              </div>
            </div>

            <hr className="border-line" />

            {/* Input Mode Toggle */}
            <div className="space-y-2.5 min-w-0">
              <label className="text-[10px] font-black text-muted uppercase tracking-widest flex items-center gap-1.5 truncate">
                <Settings2 className="w-3.5 h-3.5 text-brand shrink-0" /> 2. Conversion Method
              </label>
              
              <div className="grid grid-cols-2 gap-2.5 min-w-0">
                <button 
                  type="button"
                  onClick={() => setInputMode("size")}
                  className={`p-3.5 rounded-xl border transition-all flex flex-col items-start gap-1 min-w-0 truncate ${inputMode === "size" ? "border-brand bg-brand/5 text-ink" : "border-line bg-paper text-muted hover:text-ink"}`}
                >
                  <ArrowRightLeft className={`w-4 h-4 shrink-0 ${inputMode === "size" ? "text-brand" : "text-muted"}`} />
                  <span className="text-[10px] font-black uppercase tracking-wider truncate w-full text-left">Standard Convert</span>
                  <span className="text-[8px] font-bold text-muted truncate w-full text-left">US to UK/EU</span>
                </button>
                
                <button 
                  type="button"
                  onClick={() => setInputMode("measure")}
                  className={`p-3.5 rounded-xl border transition-all flex flex-col items-start gap-1 min-w-0 truncate ${inputMode === "measure" ? "border-brand bg-brand/5 text-ink" : "border-line bg-paper text-muted hover:text-ink"}`}
                >
                  <Ruler className={`w-4 h-4 shrink-0 ${inputMode === "measure" ? "text-brand" : "text-muted"}`} />
                  <span className="text-[10px] font-black uppercase tracking-wider truncate w-full text-left">True Measure</span>
                  <span className="text-[8px] font-bold text-muted truncate w-full text-left">By foot length (CM)</span>
                </button>
              </div>
            </div>

            <hr className="border-line" />

            {/* Actual Inputs */}
            {inputMode === "size" ? (
              <div className="space-y-3 min-w-0">
                <div className="grid grid-cols-2 gap-3 min-w-0">
                  <div className="min-w-0">
                    <label className="text-[8px] font-bold text-muted uppercase tracking-widest mb-1 block truncate">Source Region</label>
                    <select
                      value={sourceRegion} onChange={(e) => setSourceRegion(e.target.value)}
                      className={`${baseInputStyle} cursor-pointer uppercase truncate`}
                    >
                      <option value="us">US Size</option>
                      <option value="uk">UK Size</option>
                      <option value="eu">EU Size</option>
                    </select>
                  </div>
                  <div className="min-w-0">
                    <label className="text-[8px] font-bold text-muted uppercase tracking-widest mb-1 block truncate">Select Size</label>
                    <select
                      value={selectedSize} onChange={(e) => setSelectedSize(e.target.value)}
                      className={`${baseInputStyle} text-center cursor-pointer truncate`}
                    >
                      {SHOE_DATA[profile].map((item, idx) => (
                        <option key={idx} value={item[sourceRegion]}>{item[sourceRegion]}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-2.5 min-w-0">
                <label className="text-[10px] font-bold text-muted uppercase tracking-widest mb-1 block truncate">Heel to longest toe (CM)</label>
                <div className="relative flex items-center bg-paper border border-line rounded-xl overflow-hidden focus-within:border-brand min-w-0">
                  <div className="bg-surface px-3 py-3.5 flex items-center justify-center border-r border-line shrink-0">
                    <Ruler className="w-4 h-4 text-muted" />
                  </div>
                  <input
                    type="text" step="0.5" value={measuredCm} 
                    onChange={(e) => setMeasuredCm(e.target.value)}
                    placeholder="27.0"
                    className="w-full min-w-0 bg-transparent px-3 py-3 text-2xl font-black text-ink outline-none tabular-nums"
                  />
                  <span className="pr-4 text-xs font-bold text-muted uppercase tracking-wider pointer-events-none">CM</span>
                </div>
                <p className="text-[9px] font-medium text-muted flex items-center gap-1 truncate">
                  <Info className="w-3 h-3 shrink-0" /> Trace foot on paper for best accuracy.
                </p>
              </div>
            )}

          </div>
        </div>

        {/* DASHBOARD / PASSPORT */}
        <div className="space-y-6 lg:sticky lg:top-6 min-w-0">
          <div className="bg-surface border border-line p-5 sm:p-6 rounded-2xl shadow-card flex flex-col min-h-[500px] min-w-0">
            
            <div className="flex items-center justify-between mb-4 border-b border-line pb-3 shrink-0 min-w-0">
              <span className="inline-flex items-center gap-1.5 text-xs font-black uppercase tracking-widest text-ink truncate">
                <Activity className="w-4 h-4 text-brand shrink-0" /> Size Passport
              </span>
              <span className="text-[9px] font-bold uppercase tracking-wider text-muted bg-paper px-2 py-0.5 rounded border border-line shrink-0">
                {profile}
              </span>
            </div>

            {/* HERO METRIC: TRUE FIT CM */}
            <div className="text-center bg-paper border border-line py-5 px-4 rounded-xl shadow-sm mb-4 relative overflow-hidden shrink-0 min-w-0">
              <span className="block text-[9px] font-black uppercase tracking-widest text-muted mb-1 truncate">
                True Fit Foot Length
              </span>
              <div className="flex justify-center items-end gap-1 min-w-0 truncate">
                <span className="text-4xl sm:text-5xl font-black text-brand tracking-tight tabular-nums leading-none truncate">
                  {result.cm}
                </span>
                <span className="text-sm font-bold text-muted mb-1 shrink-0">CM</span>
              </div>
              
              {inputMode === "measure" && (
                <div className="mt-3 flex justify-center min-w-0">
                  <span className="text-[8px] font-black uppercase tracking-widest px-2.5 py-1 rounded-full bg-surface border border-line text-muted truncate">
                    Closest Match Auto-Selected
                  </span>
                </div>
              )}
            </div>

            {/* DETAILED SIZE GRID */}
            <div className="flex-1 flex flex-col min-h-0 bg-paper rounded-xl border border-line p-3 shadow-sm mb-4 min-w-0">
              
              <h4 className="text-[9px] font-black uppercase tracking-widest text-muted mb-3 text-center truncate">
                Official Global Conversions
              </h4>

              <div className="grid grid-cols-3 gap-2.5 min-w-0">
                <div className={`flex flex-col items-center justify-center p-3 rounded-lg border min-w-0 truncate ${sourceRegion === 'us' && inputMode === 'size' ? 'border-brand bg-brand/5' : 'border-line bg-surface'}`}>
                  <span className="text-[8px] font-bold text-muted uppercase tracking-wider truncate">US Size</span>
                  <span className="text-xl sm:text-2xl font-black text-ink truncate mt-0.5">{result.us}</span>
                </div>

                <div className={`flex flex-col items-center justify-center p-3 rounded-lg border min-w-0 truncate ${sourceRegion === 'uk' && inputMode === 'size' ? 'border-brand bg-brand/5' : 'border-line bg-surface'}`}>
                  <span className="text-[8px] font-bold text-muted uppercase tracking-wider truncate">UK Size</span>
                  <span className="text-xl sm:text-2xl font-black text-ink truncate mt-0.5">{result.uk}</span>
                </div>

                <div className={`flex flex-col items-center justify-center p-3 rounded-lg border min-w-0 truncate ${sourceRegion === 'eu' && inputMode === 'size' ? 'border-brand bg-brand/5' : 'border-line bg-surface'}`}>
                  <span className="text-[8px] font-bold text-muted uppercase tracking-wider truncate">EU Size</span>
                  <span className="text-xl sm:text-2xl font-black text-ink truncate mt-0.5">{result.eu}</span>
                </div>
              </div>

              <div className="mt-auto pt-4 flex items-start gap-2 min-w-0">
                <AlertCircle className="w-3.5 h-3.5 text-muted shrink-0 mt-0.5" />
                <p className="text-[9px] font-medium text-muted leading-relaxed truncate">
                  <strong>Fit Tip:</strong> Add 0.5 CM if measuring in the morning (swelling allowance).
                </p>
              </div>
            </div>

            {/* ACTION BUTTON */}
            <button
              type="button"
              onClick={handleCopy}
              className="w-full py-3 rounded-xl bg-ink text-surface hover:opacity-95 text-xs font-black uppercase tracking-widest transition-opacity flex items-center justify-center gap-2 shrink-0"
            >
              {copied ? <><CheckCircle2 className="w-3.5 h-3.5 shrink-0"/> Copied!</> : <><Copy className="w-3.5 h-3.5 shrink-0"/> Copy Size Passport</>}
            </button>

          </div>
        </div>

      </div>
    </div>
  );
}