"use client";

import React, { useState, useEffect, useMemo } from "react";
import {
  Globe, Ruler, ShoppingBag, Info, 
  CheckCircle2, Copy, AlertCircle, ArrowRightLeft,
  Settings2, Activity
} from "lucide-react";

// Robust Database for Global Sizing
const SHOE_DATA = {
  men: [
    { us: "6", uk: "5.5", eu: "39", cm: "24.0" },
    { us: "6.5", uk: "6", eu: "39.5", cm: "24.5" },
    { us: "7", uk: "6", eu: "40", cm: "25.0" },
    { us: "7.5", uk: "6.5", eu: "40.5", cm: "25.5" },
    { us: "8", uk: "7", eu: "41", cm: "26.0" },
    { us: "8.5", uk: "7.5", eu: "42", cm: "26.5" },
    { us: "9", uk: "8", eu: "42.5", cm: "27.0" },
    { us: "9.5", uk: "8.5", eu: "43", cm: "27.5" },
    { us: "10", uk: "9", eu: "44", cm: "28.0" },
    { us: "10.5", uk: "9.5", eu: "44.5", cm: "28.5" },
    { us: "11", uk: "10", eu: "45", cm: "29.0" },
    { us: "11.5", uk: "10.5", eu: "45.5", cm: "29.5" },
    { us: "12", uk: "11", eu: "46", cm: "30.0" },
    { us: "13", uk: "12", eu: "47.5", cm: "31.0" },
    { us: "14", uk: "13", eu: "48.5", cm: "32.0" }
  ],
  women: [
    { us: "5", uk: "3", eu: "35.5", cm: "22.0" },
    { us: "5.5", uk: "3.5", eu: "36", cm: "22.5" },
    { us: "6", uk: "4", eu: "36.5", cm: "23.0" },
    { us: "6.5", uk: "4.5", eu: "37.5", cm: "23.5" },
    { us: "7", uk: "5", eu: "38", cm: "24.0" },
    { us: "7.5", uk: "5.5", eu: "38.5", cm: "24.5" },
    { us: "8", uk: "6", eu: "39", cm: "25.0" },
    { us: "8.5", uk: "6.5", eu: "40", cm: "25.5" },
    { us: "9", uk: "7", eu: "40.5", cm: "26.0" },
    { us: "9.5", uk: "7.5", eu: "41", cm: "26.5" },
    { us: "10", uk: "8", eu: "42", cm: "27.0" },
    { us: "10.5", uk: "8.5", eu: "42.5", cm: "27.5" },
    { us: "11", uk: "9", eu: "43", cm: "28.0" },
    { us: "12", uk: "10", eu: "44.5", cm: "29.0" }
  ],
  kids: [
    { us: "1Y", uk: "13.5", eu: "32", cm: "20.0" },
    { us: "1.5Y", uk: "1", eu: "33", cm: "20.5" },
    { us: "2Y", uk: "1.5", eu: "33.5", cm: "21.0" },
    { us: "2.5Y", uk: "2", eu: "34", cm: "21.5" },
    { us: "3Y", uk: "2.5", eu: "35", cm: "22.0" },
    { us: "3.5Y", uk: "3", eu: "35.5", cm: "22.5" },
    { us: "4Y", uk: "3.5", eu: "36", cm: "23.0" },
    { us: "4.5Y", uk: "4", eu: "36.5", cm: "23.5" },
    { us: "5Y", uk: "4.5", eu: "37.5", cm: "23.5" },
    { us: "6Y", uk: "5.5", eu: "38.5", cm: "24.0" }
  ]
};

export default function ShoeSizeConverter() {
  const [isMounted, setIsMounted] = useState(false);

  // States
  const [profile, setProfile] = useState("men"); // 'men', 'women', 'kids'
  const [inputMode, setInputMode] = useState("size"); // 'size' or 'measure'
  
  // Size Mode States
  const [sourceRegion, setSourceRegion] = useState("us"); // 'us', 'uk', 'eu'
  const [selectedSize, setSelectedSize] = useState("9");
  
  // Measure Mode States
  const [measuredCm, setMeasuredCm] = useState("27.0");
  const [copied, setCopied] = useState(false);

  // Handle switching profiles (reset values to avoid crash)
  useEffect(() => {
    const data = SHOE_DATA[profile];
    if (data && data.length > 0) {
      if (inputMode === "size") {
        // Find a middle-ish value for default
        const midIndex = Math.floor(data.length / 2);
        setSelectedSize(data[midIndex][sourceRegion]);
      } else {
        const midIndex = Math.floor(data.length / 2);
        setMeasuredCm(data[midIndex].cm);
      }
    }
  }, [profile, sourceRegion, inputMode]);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  // --- CORE CONVERSION ENGINE ---
  const result = useMemo(() => {
    const data = SHOE_DATA[profile];
    
    if (inputMode === "size") {
      // Find exact match by selected region & size
      return data.find(item => item[sourceRegion] === selectedSize) || data[0];
    } else {
      // Find CLOSEST match based on CM input
      const cmVal = parseFloat(measuredCm) || 0;
      let closest = data[0];
      let minDiff = Infinity;
      
      data.forEach(item => {
        const diff = Math.abs(parseFloat(item.cm) - cmVal);
        if (diff < minDiff) {
          minDiff = diff;
          closest = item;
        }
      });
      return closest;
    }
  }, [profile, inputMode, sourceRegion, selectedSize, measuredCm]);

  const handleCopy = () => {
    const text = `👟 My Shoe Size Passport (${profile.toUpperCase()}):\nUS: ${result.us}\nUK: ${result.uk}\nEU: ${result.eu}\nFoot Length: ${result.cm} CM\n\nGenerated by Muxair Utility Engine`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isMounted) return null;

  // Dynamic Theming
  const theme = {
    gradient: profile === "men" ? "from-blue-100 via-cyan-50 to-transparent dark:from-blue-900/30 dark:via-cyan-900/10" : 
              profile === "women" ? "from-rose-100 via-pink-50 to-transparent dark:from-rose-900/30 dark:via-pink-900/10" : 
              "from-emerald-100 via-teal-50 to-transparent dark:from-emerald-900/30 dark:via-teal-900/10",
    bgIcon: profile === "men" ? "bg-gradient-to-br from-blue-500 to-cyan-500" : 
            profile === "women" ? "bg-gradient-to-br from-rose-500 to-pink-500" : 
            "bg-gradient-to-br from-emerald-500 to-teal-500",
    textPri: profile === "men" ? "text-blue-600 dark:text-blue-400" : 
             profile === "women" ? "text-rose-600 dark:text-rose-400" : 
             "text-emerald-600 dark:text-emerald-400",
    borderLight: profile === "men" ? "border-blue-200 dark:border-blue-800" : 
                 profile === "women" ? "border-rose-200 dark:border-rose-800" : 
                 "border-emerald-200 dark:border-emerald-800",
    bgLight: profile === "men" ? "bg-blue-50 dark:bg-blue-900/20" : 
             profile === "women" ? "bg-rose-50 dark:bg-rose-900/20" : 
             "bg-emerald-50 dark:bg-emerald-900/20"
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6 font-sans">
      
      {/* Premium Header */}
      <div className={`flex flex-wrap items-center justify-between gap-4 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 px-6 py-6 rounded-2xl shadow-sm relative overflow-hidden transition-colors duration-500`}>
        <div className={`absolute top-0 right-0 w-72 h-72 bg-gradient-to-bl ${theme.gradient} rounded-bl-full -z-10 opacity-70 transition-colors duration-500`}></div>
        <div className="flex items-center gap-4">
          <div className={`${theme.bgIcon} p-3.5 rounded-2xl shadow-md transition-colors duration-500`}>
            <Globe className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-black text-slate-800 dark:text-slate-100 tracking-tight">
              Global Sizing Engine
            </h2>
            <p className="text-[11px] font-bold uppercase tracking-widest text-slate-400 mt-1">
              Universal Shoe Size & Fit Converter
            </p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr,460px] gap-6 items-start">
        
        {/* ================= LEFT: CONFIGURATION ENGINE ================= */}
        <div className="space-y-6">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 sm:p-8 rounded-3xl shadow-sm space-y-8">
            
            {/* 1. Demographic Profile */}
            <div className="space-y-4">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-400 flex items-center gap-1.5 border-b border-slate-100 dark:border-slate-800 pb-2">
                <ShoppingBag className={`w-3.5 h-3.5 ${theme.textPri}`} /> 1. Select Demographic
              </h3>
              
              <div className="flex bg-slate-100 dark:bg-slate-800 rounded-xl p-1 shadow-inner">
                <button 
                  onClick={() => setProfile("men")}
                  className={`flex-1 py-3 text-xs font-black uppercase tracking-widest rounded-lg transition-all ${profile === "men" ? "bg-white dark:bg-slate-700 text-blue-600 shadow-sm" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
                >
                  Men
                </button>
                <button 
                  onClick={() => setProfile("women")}
                  className={`flex-1 py-3 text-xs font-black uppercase tracking-widest rounded-lg transition-all ${profile === "women" ? "bg-white dark:bg-slate-700 text-rose-600 shadow-sm" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
                >
                  Women
                </button>
                <button 
                  onClick={() => setProfile("kids")}
                  className={`flex-1 py-3 text-xs font-black uppercase tracking-widest rounded-lg transition-all ${profile === "kids" ? "bg-white dark:bg-slate-700 text-emerald-600 shadow-sm" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
                >
                  Youth / Kids
                </button>
              </div>
            </div>

            {/* 2. Input Mode Toggle */}
            <div className="space-y-4">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-slate-400 flex items-center gap-1.5 border-b border-slate-100 dark:border-slate-800 pb-2">
                <Settings2 className={`w-3.5 h-3.5 ${theme.textPri}`} /> 2. Conversion Method
              </h3>
              
              <div className="grid grid-cols-2 gap-3">
                <button 
                  onClick={() => setInputMode("size")}
                  className={`p-4 rounded-2xl border-2 transition-all flex flex-col items-start gap-1.5 ${inputMode === "size" ? `${theme.borderLight} ${theme.bgLight}` : "border-slate-200 dark:border-slate-700 hover:border-slate-300 bg-slate-50 dark:bg-slate-800/50"}`}
                >
                  <ArrowRightLeft className={`w-5 h-5 ${inputMode === "size" ? theme.textPri : "text-slate-400"}`} />
                  <span className={`text-xs font-black uppercase tracking-widest ${inputMode === "size" ? theme.textPri : "text-slate-600 dark:text-slate-400"}`}>Standard Convert</span>
                  <span className="text-[10px] font-bold text-slate-400 text-left">Convert US to UK, EU, etc.</span>
                </button>
                
                <button 
                  onClick={() => setInputMode("measure")}
                  className={`p-4 rounded-2xl border-2 transition-all flex flex-col items-start gap-1.5 ${inputMode === "measure" ? `${theme.borderLight} ${theme.bgLight}` : "border-slate-200 dark:border-slate-700 hover:border-slate-300 bg-slate-50 dark:bg-slate-800/50"}`}
                >
                  <Ruler className={`w-5 h-5 ${inputMode === "measure" ? theme.textPri : "text-slate-400"}`} />
                  <span className={`text-xs font-black uppercase tracking-widest ${inputMode === "measure" ? theme.textPri : "text-slate-600 dark:text-slate-400"}`}>True Measure (CM)</span>
                  <span className="text-[10px] font-bold text-slate-400 text-left">Find size by foot length</span>
                </button>
              </div>
            </div>

            <hr className="border-slate-100 dark:border-slate-800" />

            {/* 3. The Actual Inputs based on mode */}
            {inputMode === "size" ? (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5 block">Source Region</label>
                    <select
                      value={sourceRegion} onChange={(e) => setSourceRegion(e.target.value)}
                      className="w-full bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-xl px-4 py-4 text-sm font-black text-slate-800 dark:text-slate-100 outline-none focus:border-slate-400 cursor-pointer uppercase tracking-widest"
                    >
                      <option value="us">US Size</option>
                      <option value="uk">UK Size</option>
                      <option value="eu">EU Size</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5 block">Select Size</label>
                    <select
                      value={selectedSize} onChange={(e) => setSelectedSize(e.target.value)}
                      className={`w-full bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-xl px-4 py-4 text-lg font-black text-slate-800 dark:text-slate-100 outline-none cursor-pointer focus:border-slate-400 transition-colors`}
                    >
                      {SHOE_DATA[profile].map((item, idx) => (
                        <option key={idx} value={item[sourceRegion]}>{item[sourceRegion]}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-4 animate-in fade-in slide-in-from-bottom-2">
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1.5 block">Measure your foot (Heel to longest toe)</label>
                <div className={`relative flex items-center bg-slate-50 dark:bg-slate-800/50 border-2 border-slate-200 dark:border-slate-700 rounded-2xl overflow-hidden focus-within:border-slate-400 transition-all`}>
                  <div className="bg-slate-100 dark:bg-slate-800 px-5 py-5 flex items-center justify-center border-r border-slate-200 dark:border-slate-700">
                    <Ruler className="w-5 h-5 text-slate-400" />
                  </div>
                  <input
                    type="number" step="0.5" value={measuredCm} 
                    onChange={(e) => setMeasuredCm(e.target.value)}
                    placeholder="27.0"
                    className="w-full bg-transparent px-5 py-5 text-3xl font-black text-slate-800 dark:text-slate-100 outline-none tabular-nums"
                  />
                  <span className="pr-6 text-sm font-bold text-slate-400 uppercase tracking-widest">CM</span>
                </div>
                <p className="text-[10px] font-medium text-slate-500 mt-2 flex items-center gap-1.5">
                  <Info className="w-3.5 h-3.5" /> For best results, trace your foot on a paper and measure with a ruler.
                </p>
              </div>
            )}

          </div>
        </div>

        {/* ================= RIGHT: THE DASHBOARD / PASSPORT ================= */}
        <div className="space-y-6 sticky top-6">
          <div className="bg-white dark:bg-[#0d1117] border border-slate-200 dark:border-slate-800 p-1 rounded-3xl shadow-lg relative flex flex-col min-h-[600px]">
            <div className="bg-slate-50 dark:bg-slate-900/50 rounded-[22px] p-6 h-full flex flex-col relative overflow-hidden">
              
              <div className="flex items-center justify-between mb-4 border-b border-slate-200 dark:border-slate-700 pb-4 shrink-0">
                <span className="inline-flex items-center gap-1.5 text-xs font-black uppercase tracking-widest text-slate-800 dark:text-slate-100">
                  <Activity className={`w-4 h-4 ${theme.textPri}`} /> Size Passport
                </span>
                <span className={`text-[9px] font-bold uppercase tracking-widest ${theme.textPri} bg-white dark:bg-slate-800 px-2 py-1 rounded shadow-sm border border-slate-100 dark:border-slate-700`}>
                  {profile} Profiling
                </span>
              </div>

              {/* HERO METRIC: TRUE FIT CM */}
              <div className="text-center bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 py-6 px-4 rounded-3xl shadow-sm mb-6 relative overflow-hidden shrink-0">
                <div className="absolute -left-4 -bottom-4 opacity-5 pointer-events-none">
                  <Ruler className={`w-32 h-32 ${theme.textPri}`} />
                </div>
                
                <span className="block text-[11px] font-black uppercase tracking-widest text-slate-400 mb-2 z-10 relative">
                  The "True Fit" Foot Length
                </span>
                <div className="flex justify-center items-end gap-1 z-10 relative">
                  <span className={`text-6xl font-black ${theme.textPri} tracking-tighter tabular-nums leading-none block`}>
                    {result.cm}
                  </span>
                  <span className="text-xl font-bold text-slate-300 dark:text-slate-600 mb-1">CM</span>
                </div>
                
                {inputMode === "measure" && (
                  <div className="mt-4 flex justify-center z-10 relative">
                    <span className="text-[9px] font-black uppercase tracking-widest px-3 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 border border-slate-200 dark:border-slate-700">
                      Closest Match Automatically Selected
                    </span>
                  </div>
                )}
              </div>

              {/* DETAILED SIZE GRID */}
              <div className="flex-1 flex flex-col min-h-0 bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 p-4 shadow-sm mb-4">
                
                <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-4 text-center">
                  Official Global Conversions
                </h4>

                <div className="grid grid-cols-3 gap-3">
                  
                  {/* US Block */}
                  <div className={`flex flex-col items-center justify-center p-4 rounded-xl border ${sourceRegion === 'us' && inputMode === 'size' ? `${theme.borderLight} ${theme.bgLight}` : 'border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50'}`}>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">US Size</span>
                    <span className="text-2xl font-black text-slate-800 dark:text-slate-100">{result.us}</span>
                  </div>

                  {/* UK Block */}
                  <div className={`flex flex-col items-center justify-center p-4 rounded-xl border ${sourceRegion === 'uk' && inputMode === 'size' ? `${theme.borderLight} ${theme.bgLight}` : 'border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50'}`}>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">UK Size</span>
                    <span className="text-2xl font-black text-slate-800 dark:text-slate-100">{result.uk}</span>
                  </div>

                  {/* EU Block */}
                  <div className={`flex flex-col items-center justify-center p-4 rounded-xl border ${sourceRegion === 'eu' && inputMode === 'size' ? `${theme.borderLight} ${theme.bgLight}` : 'border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50'}`}>
                    <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">EU Size</span>
                    <span className="text-2xl font-black text-slate-800 dark:text-slate-100">{result.eu}</span>
                  </div>

                </div>

                {/* Pro Tips Insight */}
                <div className="mt-auto pt-6 flex items-start gap-2">
                  <AlertCircle className="w-4 h-4 text-slate-400 shrink-0 mt-0.5" />
                  <p className="text-[10px] font-medium text-slate-500 leading-relaxed">
                    <strong>Pro Fit Tip:</strong> Feet tend to swell during the day. If you measured your feet in the morning, consider adding 0.5 CM to ensure they fit perfectly by evening. For sports shoes, leave a thumb's width at the toe.
                  </p>
                </div>
              </div>

              {/* ACTION BUTTON */}
              <button
                onClick={handleCopy}
                className="w-full py-4 rounded-xl bg-slate-800 dark:bg-slate-100 hover:bg-slate-700 dark:hover:bg-white text-white dark:text-slate-900 text-xs font-black uppercase tracking-widest transition-colors flex items-center justify-center gap-2 shrink-0"
              >
                {copied ? <><CheckCircle2 className="w-4 h-4"/> Saved to Clipboard!</> : <><Copy className="w-4 h-4"/> Copy Size Passport</>}
              </button>

            </div>
          </div>
        </div>

      </div>
    </div>
  );
}